#!/usr/bin/env node
const path = require('path');
const fs = require('fs');
const execFile = require('child_process').execFile;
const exec = require('child_process').exec;

const hookName = path.basename(__filename);
const userHooks = path.join(__dirname, '../../hooks')
const hookFile = require(path.join(__dirname, '../../hookman.json'));
const hookExecutable = path.join(userHooks, hookName) 
const hookExecutableExists = fs.existsSync(hookExecutable); 
const hookScript = hookFile[hookName]; 

function handler(error, stdout, stderr) {

  if(stdout) {
    console.log(stdout);
  }

  if(stderr) {
    console.log(stderr);
  }
  if (error || stderr) {
    console.log(`Hookman: ${hookName} check failed.`);
    process.exit(1); 
  }

  process.exit(0);    
}

if (hookScript) {
  const child = exec(hookScript, handler);
}

if (hookExecutableExists) {
  const child = execFile(hookExecutable, [], handler);
}
